---
- name: "create folder"
  file:
    path: /home/ubuntu/udapeople
    state: directory
- name: "copy files"
  copy:
    src: artifact.tar.gz
    destination: /home/ubuntu/udapeople/artifact.tar.gz
    backup: yes
- name: "uncompress files"
  shell: |
    cd /home/ubuntu/udapeople
    tar xvzf artifact.tar.gz -C .
    ls -la
