---
- name: "create folder"
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: "copy files"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople/artifact.tar.gz
    backup: yes

- name: "uncompress files"
  shell: |
    cd /home/ubuntu/udapeople
    tar xvzf artifact.tar.gz -C .

- name: "run app"
  become: yes
  shell: |
    cd /home/ubuntu/udapeople
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: /home/ubuntu/udapeople
